### ISSUE TITLE
[Feature Request] Ruler and grid

### ISSUE THREAD

**Issue by mudin** [salgum1114/react-design-editor#94]
Hello!
Thanks for the great work.
I really like the editor.
Is there future plan to add ruler and grid?
[jcanvas](https://www.janvas.com/v6.1/janvas_app_6.1_public/index.html) has really cool one.
![Screen Shot 2019-04-03 at 4 05 06 PM](https://user-images.githubusercontent.com/33612405/55459526-be219d80-562a-11e9-8676-812cd61fcd26.png)
It'd be awesome and useful if those features will be added in the near future.
Best regards,
Mudin

**Comment by salgum1114** [comment]
Hi, mudin!

First, thank you for your interest in this project 👍 

The current grid exists, and plan to add the ruler!

![image](https://user-images.githubusercontent.com/19975642/55462552-01cbd580-5632-11e9-90fe-6b164b8708f6.png)

I'm grateful for your idea and will soon be able to see the ruler and grid functions together.

Thanks mudin! 👍 👍 👍 👍 👍

**Comment by mudin** [comment]
@salgum1114 Perfect! Ive just seen it in Workflow tab. 
Can it be applied for Image Map too?
How to make the zoom level deeper?

**Comment by salgum1114** [comment]
@mudin 

Because the **Canvas.js** Component has a grid props, It is also available in Image Map.

In the case of Image Map, the values of minZoom and maxZoom default prop are 30% and 300%.

In the case of Workflow, the values of minZoom and maxZoom default prop are 50% and 150%.

If you want to deep more than that, you can increase the value of maxZoom.

**Comment by mudin** [comment]
@salgum1114 I see. That's good then. Thanks a lot

**Comment by salgum1114** [comment]
👍
